#!/bin/sh
set -e
title="$1"
if [ -z "$title" ]; then
  printf "Title: "
  read -r title
fi

slug=$(echo "$title" | sed 's/[^a-zA-Z0-9 ]//g' | sed 's/[[:space:]]/-/g')
file="_drafts/$slug.md"

cat > "$file" <<EOS
---
title: $title
description:
series:
tags:
- TODO
---

EOS
git add "$file"

case "$EDITOR" in
  *vim) "$EDITOR" "+ normal Go" -c startinsert "$file";;
  *) "$EDITOR" "$file";;
esac
git add "$file"

git commit --allow-empty-message -m ''
git push origin
