#!/bin/sh
set -e

basename="$1"
if [ -z "$1" ]; then
  echo "Usage: <draft basename>"
  exit 1
fi

draft="_drafts/$basename.md"
if ! [ -f "$draft" ]; then
  echo "No such draft: $draft." >/dev/stderr
  exit 1
fi

today="$(date --iso-8601)"
post="_posts/$today-$basename.md"
git mv "$draft" "$post"
now="$(date --iso-8601=seconds)"
sed --in-place "s/^title: \\(.\\+\\)$/date: $now\\ntitle: \\1/"
git add "$post"
git commit --allow-empty-message --message ''
git push
