#!/bin/sh
set -e

basename="$1"
if [ -z "$1" ]; then
  basename="$(basename "$(find _drafts -iname "*.md" | fzf)" .md)"
fi

draft="_drafts/$basename.md"
if ! [ -f "$draft" ]; then
  echo "No such draft: $draft." >/dev/stderr
  exit 1
fi

date="$(date --iso-8601)"
post="_posts/$date-$basename.md"
git mv "$draft" "$post"
time="$(date --iso-8601=seconds)"
sed --in-place "s/^title: \\(.\\+\\)$/date: $time\\ntitle: \\1/" "$post"
git add "$post"
git commit --allow-empty-message --message ''
sleep 2s
git push
